


app:
  service:
    accuweather:
      forecastUrl: http://dataservice.accuweather.com/forecasts/v1/daily/1day/{locationKey}
      searchCityUrl: http://dataservice.accuweather.com/locations/v1/cities/search
      apikey: ${ACCUWEATHER_API_KEY}