


app:
  service:
    accuweather:
      forecastUrl: http://dataservice.accuweather.com/forecasts/v1/daily/1day/{locationKey}
      currentUrl: http://dataservice.accuweather.com/currentconditions/v1/{locationKey}
      searchCityUrl: http://dataservice.accuweather.com/locations/v1/cities/search
      apikey: ${ACCUWEATHER_API_KEY}
      array:
        - one
        - two
        - three
        - four
    openweather:
      currentUrl: http://api.openweathermap.org/data/2.5/weather
      apikey: ${OPENWEATHER_API_KEY}


spring:
  security:
    user:
      name: user
      password: heslo
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
#            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update